### ISSUE TITLE
rbt_release missing file

### ISSUE THREAD

**Issue by BELKHIR** [koesterlab/rad-seq-stacks#1]
Hi,
The shell command in the rule "generate_consensus_reads" make a call to a command named rbt_release which is missing in the repo.

This is also missing in the dependencies section of envs/consensus.yaml

Regards

**Comment by johanneskoester** [comment]
Thanks, this is still in development. The version of rbt that allows to call consensus reads has yet to be released.

**Comment by johanneskoester** [comment]
Fixed now. Thanks again. Any other feedback or contributions would be greatly appreciated!
