### ISSUE TITLE
Samples.tsv format

### ISSUE THREAD

**Issue by susheelbhanu** [koesterlab/rad-seq-stacks#22]
Hi @johanneskoester, 

Is it possible to run this analyses starting from raw reads? Also, could you provide an example of the `samples.tsv` file?

Thank you,
Susheel

**Comment by HenningTimm** [comment]
Yes, you should be able to run this for raw RADseq reads. This pipeline expects unmultiplexed FASTQ files as input. However, it does not perform quality filtering.

About the `samples.tsv`: Sorry, the documentation is not up to date. The samples are specified in the files `units.tsv` containing the barcoding information etc. and `individuals.tsv` containing information about the individuals. You can find a small example in the [tests for this workflow](https://github.com/snakemake-workflows/rad-seq-stacks/tree/master/.test/integration_test/config). You can find a more realistic sample sheet over in [this project](https://github.com/HenningTimm/rad-seq-stacks_evaluation/tree/master/05_analyzing_a_large_dataset/pipeline_no_dedup).

**Comment by susheelbhanu** [comment]
Awesome, thank you 🙏
